"""Immutable pre-refactoring references for cache, statistics and checkpoints.

The expected values were generated by P0, not by the implementation under test.
Do not regenerate these fixtures to accommodate a refactoring regression.
"""
import hashlib
import json
from pathlib import Path

import pytest
import torch

import mtlearn
from mtlearn.layers import ConnectedFilterPreprocessingLayer, load_checkpoint

pytestmark = pytest.mark.integration
if not getattr(mtlearn, 'WITH_TORCH', False):
    pytest.skip('build has no LibTorch support', allow_module_level=True)

FIXTURES = Path(__file__).parent / 'fixtures' / 'cfp_cache_p0'
MANIFEST = json.loads((FIXTURES / 'manifest.json').read_text())
CASE_NAMES = MANIFEST['cases']


@pytest.fixture(scope='module')
def reference():
    return torch.load(FIXTURES / 'baseline.pt', map_location='cpu', weights_only=True)


def assert_nested_close(actual, expected):
    if torch.is_tensor(expected):
        torch.testing.assert_close(actual.cpu(), expected.cpu(), rtol=1e-10, atol=1e-12)
    elif isinstance(expected, dict):
        assert actual.keys() == expected.keys()
        for key in expected:
            assert_nested_close(actual[key], expected[key])
    elif isinstance(expected, (tuple, list)):
        assert len(actual) == len(expected)
        for a, e in zip(actual, expected):
            assert_nested_close(a, e)
    else:
        assert actual == expected


def test_frozen_file_integrity():
    for name, expected in MANIFEST['files'].items():
        assert hashlib.sha256((FIXTURES / name).read_bytes()).hexdigest() == expected, name


@pytest.mark.parametrize('execution', ['direct', 'cached'])
@pytest.mark.parametrize('name', CASE_NAMES)
def test_pre_refactoring_checkpoint_outputs_and_gradients(reference, name, execution):
    case = reference['cases'][name]
    model, _ = load_checkpoint(
        FIXTURES / case['checkpoint'],
        lambda configs: ConnectedFilterPreprocessingLayer.from_config(configs[''], device='cpu'),
        device='cpu',
    )
    assert_outputs_and_gradients(reference, case, model, 'cpu', execution)


@pytest.mark.parametrize('execution', ['direct', 'cached'])
@pytest.mark.parametrize('name', CASE_NAMES)
def test_mps_outputs_and_gradients_against_cpu_reference(reference, name, execution):
    if not torch.backends.mps.is_available():
        pytest.skip('MPS not available')
    case = reference['cases'][name]
    model = ConnectedFilterPreprocessingLayer.from_config(case['config'], device='mps')
    indices = reference['train_indices']
    dataset = torch.utils.data.TensorDataset(reference['images'][indices], reference['targets'][indices])
    model.build_dataloader_cached(torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=False))
    # MPS statistics fitting works; deserializing float64 extra state does not.
    # Copy only the frozen trained parameters to test the supported execution path.
    state = torch.load(FIXTURES / case['checkpoint'], map_location='cpu', weights_only=True)['model_state_dict']
    with torch.no_grad():
        for param_name, parameter in model.named_parameters():
            parameter.copy_(state[param_name])
    assert_outputs_and_gradients(reference, case, model, 'mps', execution)


def assert_outputs_and_gradients(reference, case, model, device, execution):
    assert model.get_parameter_contract() == case['contracts']['parameter_contract']
    assert model.get_inference_contract() == case['contracts']['inference_contract']
    assert_nested_close(model.get_extra_state()['ds_stats'], case['stats'])
    images = reference['images'][reference['test_indices']]
    targets = reference['targets'][reference['test_indices']]
    if execution == 'cached':
        dataset = torch.utils.data.TensorDataset(images, targets)
        cached_loader = model.build_dataloader_cached_fixed_stats(
            torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=False), index_offset=100,
        )
        cached_input, _ = next(iter(cached_loader))
        output = model(cached_input)
    else:
        output = model(images)
    # Neither evaluation path may contribute the held-out samples to the fit.
    assert_nested_close(model.get_extra_state()['ds_stats'], case['stats'])
    targets = targets.to(device)
    loss = ((output / 255.0 - targets) ** 2).mean()
    loss.backward()
    tolerance = MANIFEST['cpu_mps_tolerance' if device == 'mps' else 'same_device_tolerance']
    torch.testing.assert_close(output.detach().cpu(), case['output'], **tolerance)
    torch.testing.assert_close(loss.detach().cpu(), case['loss'], **tolerance)
    actual_parameters = dict(model.named_parameters())
    assert actual_parameters.keys() == case['gradients'].keys()
    for param_name, expected in case['gradients'].items():
        assert actual_parameters[param_name].grad is not None
        torch.testing.assert_close(actual_parameters[param_name].grad.cpu(), expected, **tolerance)


@pytest.mark.parametrize('name', CASE_NAMES)
def test_training_statistics_match_pre_refactoring_reference(reference, name):
    case = reference['cases'][name]
    model = ConnectedFilterPreprocessingLayer.from_config(case['config'], device='cpu')
    indices = reference['train_indices']
    dataset = torch.utils.data.TensorDataset(reference['images'][indices], reference['targets'][indices])
    model.build_dataloader_cached(torch.utils.data.DataLoader(dataset, batch_size=2, shuffle=False))
    assert_nested_close(model.get_extra_state()['ds_stats'], case['stats'])
    # Also load the separately saved legacy normalization artifact.
    model.load_stats(FIXTURES / f'{name}.stats.pt')
    assert_nested_close(model.get_extra_state()['ds_stats'], case['stats'])


@pytest.mark.parametrize('entrypoint', ['load_checkpoint', 'load_state_dict', 'load_stats'])
def test_legacy_mps_statistics_deserialization(reference, entrypoint):
    if not torch.backends.mps.is_available():
        pytest.skip('MPS not available')
    name = 'max-tree_linear_dataset_clipped_zscore01'
    case = reference['cases'][name]
    path = FIXTURES / case['checkpoint']
    if entrypoint == 'load_checkpoint':
        model, _ = load_checkpoint(
            path,
            lambda configs: ConnectedFilterPreprocessingLayer.from_config(configs[''], device='mps'),
            device='mps',
        )
    else:
        model = ConnectedFilterPreprocessingLayer.from_config(case['config'], device='mps')
        if entrypoint == 'load_stats':
            model.load_stats(FIXTURES / f'{name}.stats.pt')
        else:
            checkpoint = torch.load(path, map_location='cpu', weights_only=True)
            model.load_state_dict(checkpoint['model_state_dict'])

    assert_nested_close(model.get_extra_state()['ds_stats'], case['stats'])
    for values in model.get_extra_state()['ds_stats'].values():
        assert all(tensor.device.type == 'cpu' for tensor in values.values())
    with torch.no_grad():
        output = model(reference['images'][reference['test_indices']])
    assert torch.isfinite(output).all()
    if entrypoint != 'load_stats':
        torch.testing.assert_close(output.cpu(), case['output'], **MANIFEST['cpu_mps_tolerance'])
